---
#mongoDB installation
- name: Add an apt key for mongoDB from ubuntu keyserver
  tags: install
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: EA312927

- name: Add mongodb repo to apt source list
  tags: install
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
    filename: mongodb-org-3.2

- name: Install mongoDB-server
  tags: install
  apt:
    name: mongodb-org
    state: present
    autoclean: yes
    autoremove: yes

- name: Enable mongoDB service
  tags: install
  systemd: name=mongod enabled=yes
